-- Creating view PRESENTATION_VW
CREATE VIEW PRESENTATION_VW AS
    SELECT COMPANY.NAME AS BOOKED_COMPANY,
           ROOM.ROOM_ID AS ROOM_NUMBER,
           ROOM.FLOOR_NUMBER AS FLOOR,
           ROOM.SEAT_CAPACITY AS SEAT,
           START_TIME,
           END_TIME
      FROM PRESENTATION
           INNER JOIN
           COMPANY ON PRESENTATION.BOOKED_COMPANY_ID = COMPANY.COMPANY_ID
           INNER JOIN
           ROOM ON PRESENTATION.BOOKED_ROOM_ID = ROOM.ROOM_ID;
